# Change these first
owner: efecear # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: efece.ar
    url: https://www.efece.ar
    icon: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  - name: Sandra Luna
    url: https://www.sandraluna.com.ar
    icon: https://www.sandraluna.com.ar/wp-content/uploads/2021/04/apple-touch-icon-57x57-precomposed1.png
  - name: Valentina Música
    check: "tcp-ping"
    port: 80
    url: https://valentina.musica.ar
    icon: https://valentina.musica.ar/wp-content/uploads/2020/04/cropped-external-content.duckduckgo.com_-32x32.png  
  - name: La Semilla Que Crece
    url: https://www.lasemillaquecrece.com.ar
    icon: https://www.lasemillaquecrece.com.ar/wp-content/uploads/2020/08/icono.jpg
  - name: Maiá Noé
    url: https://www.maianoe.com.ar
  - name: Almacén BioPandora
    check: "tcp-ping"
    port: 80
    url: https://www.biopandora.com.ar
  - name: Abocado Cantina
    url: https://www.abocado.com.ar
  - name: Almacén Reina Batata
    url: https://www.reina-batata.com.ar
  - name: Tierra Firme
    check: "tcp-ping"
    port: 80
    url: https://www.tierrafirmenodoutt.com.ar
  - name: Nodo UTT Ramos Mejia
    url: https://www.uttnodoramosmejia.com.ar
  - name: Nodo UTT Morón
    check: "tcp-ping"
    port: 80
    url: https://www.nodouttmoron.com.ar
  - name: Vía Judicial
    url: https://www.viajudicial.com.ar
  - name: FecaM
    url: https://www.fecam.com.ar
  - name: Nodo UTT Florida
    url: https://www.nodo-florida.net.ar
  - name: Jorge Retamoza Web
    url: https://www.retamoza.com.ar

assignees:
  - efecear

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.efece.ar
  baseUrl: /
  #logoUrl: https://efece.ar/wp-content/uploads/2021/08/logo-300x300.png
  name: Estado de Servicios | efece.ar
  introTitle: "Monitor de actividad en tiempo real. "
  introMessage: Nos encargamos de todos los aspectos técnicos para brindarte soluciones. Aquí el estado del servicio con **datos en tiempo real**. Si tienes un incidente/inconveniente que aún no está reportado puedes [escribinos](https://efece.ar/#contact).
  theme: light
  favicon: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  faviconSvg: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  navbar:
  #  - title: Status
  #    href: /
  #  - title: Web
  #    href: https://efece.ar
  
i18n:
  activeIncidents: Incidentes activos registrados
  allSystemsOperational: Todos los sistemas están operativos. 
  incidentReport: "Ver incidente #$NUMBER →"
  activeIncidentSummary: Iniciado el $DATE con $POSTS registros
  incidentTitle: Detalles del incidente $NUMBER
  incidentDetails: Detalles del incidente
  incidentFixed: Reparado
  incidentOngoing: En curso
  incidentOpenedAt: Abierto el
  incidentClosedAt: Cerrado el
  incidentViewOnGitHub: Acceder al GitHub
  incidentCommentSummary: Publicado el $DATE por $AUTHOR 
  incidentBack: ← Volver a todos los incidentes 
  pastIncidents: Incidentes pasados
  pastIncidentsResolved: Resuelto en $MINUTES minutos con $POSTS intervensiones
  liveStatus: Estado en vivo 
  overallUptime: "Tiempo de actividad general: $UPTIME"
  overallUptimeTitle: Tiempo de actividad general 
  averageResponseTime: "Tiempo promedio de respuesta: $TIMEms"
  averageResponseTimeTitle: Respuesta promedio
  sevelDayResponseTime: 7-day response time
  responseTimeMs: Tiempo de respuesta (ms)
  up: En Linea
  down: Caido
  degraded: Degradado
  ms: ms
  loading: Loading
  navGitHub: GitHub
  footer: Adaptación del proyecto [Upptime open source]($REPO), powered by [efece.ar](https://efece.ar/)
  rateLimitExceededTitle: Excede el límite de velocidad
  rateLimitExceededIntro: Ha superado el número de solicitudes que puede realizar en una hora, por lo que tendrá que esperar antes de volver a acceder a este sitio web. Alternativamente, puede agregar un token de acceso personal de GitHub para continuar usando este sitio web.
  rateLimitExceededWhatDoesErrorMean: ¿Qué significa este error? 
  rateLimitExceededErrorMeaning: Este sitio web utiliza la API de GitHub para acceder a datos en tiempo real sobre el estado de nuestros sitios web. De manera predeterminada, GitHub permite que cada dirección IP realice 60 solicitudes por hora, las que ha consumido.
  rateLimitExceededErrorHowCanFix: ¿Cómo puedo arreglarlo? 
  rateLimitExceededErrorFix: Puede esperar otra hora y se restablecerá el límite de su dirección IP. Como alternativa, puede agregar su token de acceso personal de GitHub, que le brinda 5000 solicitudes adicionales por hora. 
  errorTitle: Ocurrió un error
  errorIntro: Se produjo un error al intentar obtener los detalles de estado más recientes.
  errorText: Puedes volver a intentarlo en unos momentos.
  errorHome: Ir a la pagina principal
  pastScheduledMaintenance: Mantenimientos programado pasados
  scheduledMaintenance: Mantenimiento Programado
  scheduledMaintenanceSummaryStarted: Comenzó el $DATE por $DURATION minutos
  scheduledMaintenanceSummaryStarts: Comienza el $DATE por $DURATION minutos
  startedAt: Empezó a las
  startsAt: Empieza a
  duration: Duración
  durationMin: $DURATION minutos
  incidentCompleted: Terminado
  incidentScheduled: Programado

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  uptime: "*/120 * * * *"
