# Change these first
owner: efecear # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: efece.ar
    url: https://www.efece.ar
    icon: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  - name: Sandra Luna
    url: https://www.sandraluna.com.ar
  - name: La Semilla Que Crece
    url: https://www.lasemillaquecrece.com.ar
  - name: Maiá Noé
    url: https://www.maianoe.com.ar
  - name: Almacén BioPandora
    url: https://www.biopandora.com.ar
  - name: Abocado Cantina
    url: https://www.abocado.com.ar
  - name: Almacén Reina Batata
    url: https://www.reina-batata.com.ar
  - name: Tierra Firme
    url: https://www.tierrafirmenodoutt.com.ar
  - name: Nodo UTT Ramos Mejia
    url: https://www.uttnodoramosmejia.com.ar
  - name: Nodo UTT Morón
    url: https://www.nodouttmoron.com.ar
  - name: Vía Judicial
    url: https://www.viajudicial.com.ar
  - name: FecaM
    url: https://www.fecam.com.ar
  - name: Valentina Música
    url: https://www.valentina.musica.ar

assignees:
  - efecear

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: estado.efece.ar/
  baseUrl: /upptime
  #logoUrl: https://efece.ar/wp-content/uploads/2021/08/logo-300x300.png
  name: Estado Servicio efece.ar
  introTitle: "Monitor de tiempo de actividad. "
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  theme: light
  favicon: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  faviconSvg: https://efece.ar/wp-content/uploads/2021/08/logo-150x150.png
  navbar:
  #  - title: Status
  #    href: /
  #  - title: Web
  #    href: https://efece.ar
  
i18n:
  footer: Adaptación del proyecto [Upptime open source]($REPO), powered by [efece.ar](https://efece.ar/)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
